# SPDX-FileCopyrightText: 2023 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: AGPL-3.0-only

repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v1.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [ commit-msg ]
        args: [ ]

  - repo: https://github.com/fsfe/reuse-tool
    rev: v0.14.0
    hooks:
      - id: reuse